### ISSUE TITLE
Validate the Oracle version prior connecting

### ISSUE THREAD

**Issue by gmanev7** [Nolus-Protocol/oracle-price-feeder#6]
With the introduction of contract versions, we have the instruments to avoid potential errors of the network operators who configure and run the Nolus feeder and dispatcher.

This ticket aims to add a check at the launching of the Nolus feeder and dispatcher whether the API of the provided destination is supported.

Implement a query to oracle to obtain its package version.

Check the API-supported version using the compliancy rules defined with the Semver specification.

**Comment by KirilMihaylov** [comment]
Completed in 0769eb28fcdc2427321fd1edf7885c02edd8153d
